export const characterActionTypes = {
    FETCH_DATA_START: "FETCH_DATA_START",
    FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
    FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
    SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
  };